/**:
  ros__parameters:
    gscam_config: "nvv4l2camerasrc device=/dev/video1"
    camera_name: "narrow_stereo/right"
    camera_info_url: "file:///home/jetson/jetbot_ros/config/right.yaml"
    frame_id: "camera_right_frame"