/**:
  ros__parameters:
    gscam_config: "nvv4l2camerasrc device=/dev/video0"
    camera_name: "narrow_stereo/left"
    camera_info_url: "file:///home/jetson/jetbot_ros/config/left.yaml"
    frame_id: "camera_left_frame"