image_width: 640
image_height: 480
camera_name: narrow_stereo/right
camera_matrix:
  rows: 3
  cols: 3
  data: [648.93676,   0.     , 318.17278,
           0.     , 865.50267, 225.75056,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.168587, -0.281896, 0.000175, 0.001569, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 0.99724058,  0.05162528,  0.05334853,
         -0.05226884,  0.99857531,  0.01073838,
         -0.05271816, -0.01349722,  0.99851821]
projection_matrix:
  rows: 3
  cols: 4
  data: [1092.54903,    0.     ,  302.11471,  162.42381,
            0.     , 1092.54903,  230.47045,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
